export const ON_CLICK_START = 'ON_CLICK_START';
export const HANDLE_ON_CHANGE = 'HANDLE_ON_CHANGE';
export const HANDLE_ON_CLICK_NEXT = 'HANDLE_ON_CLICK_NEXT';
export const HANDLE_CHANGE_OPTION = 'HANDLE_CHANGE_OPTION';
export const HANDLE_ON_OPTION_CAPTURE = 'HANDLE_ON_OPTION_CAPTURE';
export const HANDLE_ON_CLICK_PREVIOUS = 'HANDLE_ON_CLICK_PREVIOUS';
export const HANDLE_ON_CLICK_SUBMIT = 'HANDLE_ON_CLICK_SUBMIT';
